services:
  - type: web
    runtime: node
    name: hostel-complaint-api
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        sync: false

  - type: web
    runtime: static
    name: hostel-complaint-web
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeployTrigger: commit
    envVars:
      - key: REACT_APP_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
